---
version: '2'
services:
  prod_app:
    environment:
      - GIT_COMMIT
    build:
      context: .
    container_name: "prod_app:${GIT_COMMIT}"
    ports:
      - "8080:8080"
  registry:
    image: "registry:2"
    container_name: registry
    ports:
      - "5000:5000"
