---
version: '2'
services:
  prod_app:
    build:
      context: .
    container_name: prod_app
    ports:
      - "8080:8080"
  registry:
    image: "registry:2"
    container_name: registry
    ports:
      - "5000:5000"
